apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app-container
        image: karthikvangari/first-app:latest
        ports:
        - containerPort: 5000

