apiVersion: v1
kind: Service
metadata:
  name: my-first-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31000 # Choose any available port in the range 30000-32767
  selector:
    app: my-first-app

